# Generated by Django 6.0.1 on 2026-04-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListenProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_url",
                    models.URLField(unique=True, verbose_name="URL эпизода (mp3)"),
                ),
                (
                    "current_time",
                    models.FloatField(
                        default=0.0, verbose_name="Текущее время в секундах"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
