# Generated by OpenCode on 2026-04-25

import django.conf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
        ("podcasts", "0002_listenprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcastfeed",
            name="rss_cache",
            field=models.JSONField(blank=True, null=True, verbose_name="Кеш RSS"),
        ),
        migrations.AddField(
            model_name="podcastfeed",
            name="rss_cache_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="podcast_bookmarks",
                to=django.conf.settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listenprogress",
            name="episode_url",
            field=models.URLField(verbose_name="URL эпизода (mp3)"),
        ),
        migrations.AddField(
            model_name="listenprogress",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listen_progress",
                to=django.conf.settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PodcastFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcast_folders",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="podcasts.podcastfeed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcast_subscriptions",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PodcastFolderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_items",
                        to="podcasts.podcastfeed",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="podcasts.podcastfolder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="podcastfolder",
            name="feeds",
            field=models.ManyToManyField(
                related_name="folders",
                through="podcasts.PodcastFolderItem",
                to="podcasts.podcastfeed",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=("user", "feed"), name="unique_user_bookmark"
            ),
        ),
        migrations.AddConstraint(
            model_name="listenprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "episode_url"), name="unique_user_episode_progress"
            ),
        ),
        migrations.AddConstraint(
            model_name="podcastfolder",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_folder"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "feed"), name="unique_user_subscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="podcastfolderitem",
            constraint=models.UniqueConstraint(
                fields=("folder", "feed"), name="unique_folder_feed"
            ),
        ),
    ]
